### ISSUE TITLE
Support for docker on windows

### ISSUE THREAD

**Issue by dreamuth** [xrowgmbh/docker-systemd-example-httpd#1]
I'm running docker on windows environment (with hyper v). Where I don't have access to /sys/fs/cgroup (or I'm not aware of that). Is there anyway to run this image on windows environment?

**Comment by xrow** [comment]
Hi,
I think at the moment you won't be able to run it. I can`t tell what will happen in the future.

**Comment by xrow** [comment]
can`t be solved at the moment.
